# Generated by Django 5.2.7 on 2026-05-06 03:21

import django.db.models.deletion
import restaurants.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('cuisine_type', models.CharField(choices=[('indian', 'Indian'), ('chinese', 'Chinese'), ('continental', 'Continental'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('fast_food', 'Fast Food'), ('south_indian', 'South Indian'), ('north_indian', 'North Indian'), ('bakery', 'Bakery & Desserts'), ('beverages', 'Beverages'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=restaurants.models.restaurant_image_path)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('fssai_license_number', models.CharField(max_length=20, unique=True)),
                ('business_license_number', models.CharField(blank=True, max_length=50)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=15)),
                ('opening_time', models.TimeField(default='09:00')),
                ('closing_time', models.TimeField(default='22:00')),
                ('avg_delivery_time', models.PositiveIntegerField(default=30, help_text='Average delivery time in minutes')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant Profile',
                'verbose_name_plural': 'Restaurant Profiles',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('fssai', 'FSSAI License'), ('business', 'Business License'), ('gst', 'GST Certificate'), ('pan', 'PAN Card'), ('bank', 'Bank Proof / Cancelled Cheque'), ('identity', 'Owner Identity Proof'), ('restaurant', 'Restaurant Photo'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to=restaurants.models.restaurant_doc_path)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='restaurants.restaurantprofile')),
            ],
            options={
                'verbose_name': 'Restaurant Document',
                'verbose_name_plural': 'Restaurant Documents',
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('bank', 'Bank Account'), ('upi', 'UPI ID'), ('both', 'Both')], default='bank', max_length=10)),
                ('account_holder_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('confirm_account', models.CharField(blank=True, help_text='Not stored — used only for validation', max_length=20)),
                ('ifsc_code', models.CharField(blank=True, max_length=15)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('upi_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='restaurants.restaurantprofile')),
            ],
            options={
                'verbose_name': 'Bank Details',
                'verbose_name_plural': 'Bank Details',
            },
        ),
    ]
