# Generated by Django 5.2.7 on 2026-05-10 03:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_menuitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(help_text='Promo code e.g. SAVE20', max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage Off'), ('flat', 'Flat Amount Off'), ('delivery', 'Free Delivery'), ('bogo', 'Buy 1 Get 1')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Percentage or flat amount', max_digits=6)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart value to apply offer', max_digits=8)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Max discount cap for percent type', max_digits=8, null=True)),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='restaurants.restaurantprofile')),
            ],
            options={
                'verbose_name': 'Offer',
                'ordering': ['-created_at'],
            },
        ),
    ]
